[project]
name = "fastapi-todo-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi[standard]>=0.115.11",
    "sqlalchemy>=2.0.39",
]

[dependency-groups]
dev = [
    "ruff>=0.10.0",
]
